INSERT INTO `paroki`(`id`, `nama_paroki`, `nama_dekanat`, `quota`, `created_at`, `updated_at`) VALUES  
('1','Katedral St. Petrus											','Kacikamegar	','40','',''),
('2','Odilia Cicadas												','Kacikamegar	','40','',''),
('3','St. Melania													','Kacikamegar	','40','',''),
('4','Kamuning / Salib Suci											','Kacikamegar	','40','',''),
('5','Pandu / St. Perawan Maria Sapta Kedukaan						','Palemsuci	','40','',''),
('6','Lembang / St. Maria Fatima									','Palemsuci	','40','',''),
('7','Sukajadi / Laurentius 										','Palemsuci	','40','',''),
('8','Cimahi / St. Ignatius											','Palemsuci	','40','',''),
('9','Sumber Sari/ St. Gabriel										','Dasamawartoba','40','',''),
('10','Margahayu / St. Martinus										','Dasamawartoba','40','',''),
('11','Waringin / St. Mikael										','Dasamawartoba','40','',''),
('12','Moh. Toha / St. Paulus										','Dasamawartoba','40','',''),
('13','Buah Batu / Hati Tak Bernoda Santa Perawan Maria				','Dasamawartoba','40','',''),
('14','Paroki Dayeuh Kolot											','Dasamawartoba','40','',''),
('15','Karawang / Kristus Raja										','Katabapa		','40','',''),
('16','Purwakarta / Salib Suci										','Katabapa		','40','',''),
('17','Subang / Kristus Sang Penabur								','Katabapa		','40','',''),
('18','Pamanukan / Maria Bunda Pembantu Abadi						','Katabapa		','40','',''),
('19','Cigugur / Kristus Raja										','Tasciciayu	','40','',''),
('20','Dukuh Semar - Cirebon / Bunda Maria							','Tasciciayu	','40','',''),
('21','Indramayu/St. Mikael											','Tasciciayu	','40','',''),
('22','Yos Sudarso-Cirebon / St. Yusuf								','Tasciciayu	','40','',''),
('23','Tasikmalaya / Hati Kudus Yesus								','Tasciciayu	','40','',''),
('24','Garut / Santa Perawan Maria Yang Terkandung Tak Bernoda		','Kacikamegar	','40','','')
			
